
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 18 12:27:20 CST 2024
//----------------------------------------------------

package ParserLexer;

import java_cup.runtime.Symbol;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Wed Dec 18 12:27:20 CST 2024
  */
public class lexer extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public lexer() {super();}

  /** Constructor which sets the default scanner. */
  public lexer(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public lexer(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\002\000\002\002\004\000\002\002\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\003\000\004\002\000\001\002\000\004\002\005\001" +
    "\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\003\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$lexer$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$lexer$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$lexer$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private Symbol s;
     
    public void syntax_error(Symbol s){
        this.s = s;
    }   

    public Symbol getS(){
        return this.s;
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$lexer$actions {
  private final lexer parser;

  /** Constructor */
  CUP$lexer$actions(lexer parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$lexer$do_action(
    int                        CUP$lexer$act_num,
    java_cup.runtime.lr_parser CUP$lexer$parser,
    java.util.Stack            CUP$lexer$stack,
    int                        CUP$lexer$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$lexer$result;

      /* select the action based on the action number */
      switch (CUP$lexer$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= 
            {
              Object RESULT =null;

              CUP$lexer$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$lexer$stack.peek()), ((java_cup.runtime.Symbol)CUP$lexer$stack.peek()), RESULT);
            }
          return CUP$lexer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$lexer$stack.elementAt(CUP$lexer$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$lexer$stack.elementAt(CUP$lexer$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$lexer$stack.elementAt(CUP$lexer$top-1)).value;
		RESULT = start_val;
              CUP$lexer$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$lexer$stack.elementAt(CUP$lexer$top-1)), ((java_cup.runtime.Symbol)CUP$lexer$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$lexer$parser.done_parsing();
          return CUP$lexer$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

