
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 18 11:18:29 CST 2024
//----------------------------------------------------

package code;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FinDeArchivo = 57;
  public static final int Incremento = 25;
  public static final int Coma = 47;
  public static final int MultipleLineC = 52;
  public static final int Negacion = 36;
  public static final int If = 37;
  public static final int CorcheteCierre = 11;
  public static final int Diferente = 33;
  public static final int Potencia = 24;
  public static final int Decremento = 26;
  public static final int Default = 43;
  public static final int LiteralFlotante = 18;
  public static final int Comentario = 53;
  public static final int Else = 38;
  public static final int Menor = 28;
  public static final int CorcheteApertura = 10;
  public static final int Read = 50;
  public static final int Break = 44;
  public static final int Error = 55;
  public static final int Mayor = 30;
  public static final int LiteralCadena = 16;
  public static final int ParentesisCierre = 14;
  public static final int Return = 45;
  public static final int While = 39;
  public static final int CierreBloque = 3;
  public static final int Division = 21;
  public static final int Float = 5;
  public static final int Modulo = 23;
  public static final int OneLineC = 51;
  public static final int For = 40;
  public static final int Conjuncion = 34;
  public static final int EOF = 0;
  public static final int DosPuntos = 46;
  public static final int error = 1;
  public static final int Switch = 41;
  public static final int Disyuncion = 35;
  public static final int LiteralCaracter = 15;
  public static final int SignoAsignacion = 12;
  public static final int Integer = 4;
  public static final int FinSentencia = 58;
  public static final int Linea = 54;
  public static final int Char = 7;
  public static final int Print = 49;
  public static final int Case = 42;
  public static final int MenorIgual = 29;
  public static final int String = 8;
  public static final int Negativo = 27;
  public static final int Identificador = 9;
  public static final int Resta = 20;
  public static final int MayorIgual = 31;
  public static final int Bool = 6;
  public static final int Multiplicacion = 22;
  public static final int ParentesisApertura = 13;
  public static final int Suma = 19;
  public static final int LiteralEntero = 17;
  public static final int Main = 59;
  public static final int AperturaBloque = 2;
  public static final int EspacioEnBlanco = 56;
  public static final int Igual = 32;
  public static final int LiteralBool = 48;
}

