
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 16 17:09:19 CST 2024
//----------------------------------------------------

package code;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FinDeArchivo = 52;
  public static final int Incremento = 23;
  public static final int MultipleLineC = 48;
  public static final int Negacion = 34;
  public static final int If = 35;
  public static final int CorcheteCierre = 11;
  public static final int Diferente = 31;
  public static final int Potencia = 22;
  public static final int Decremento = 24;
  public static final int Default = 41;
  public static final int Else = 36;
  public static final int Menor = 26;
  public static final int CorcheteApertura = 10;
  public static final int Read = 46;
  public static final int Break = 42;
  public static final int Error = 50;
  public static final int Mayor = 28;
  public static final int LiteralCadena = 16;
  public static final int ParentesisCierre = 14;
  public static final int Return = 43;
  public static final int While = 37;
  public static final int CierreBloque = 3;
  public static final int Division = 19;
  public static final int Float = 5;
  public static final int Modulo = 21;
  public static final int OneLineC = 47;
  public static final int For = 38;
  public static final int Conjuncion = 32;
  public static final int EOF = 0;
  public static final int DosPuntos = 44;
  public static final int error = 1;
  public static final int Switch = 39;
  public static final int Disyuncion = 33;
  public static final int LiteralCaracter = 15;
  public static final int SignoAsignacion = 12;
  public static final int Integer = 4;
  public static final int FinSentencia = 53;
  public static final int Linea = 49;
  public static final int Char = 7;
  public static final int Print = 45;
  public static final int Case = 40;
  public static final int MenorIgual = 27;
  public static final int String = 8;
  public static final int Negativo = 25;
  public static final int Identificador = 9;
  public static final int Resta = 18;
  public static final int MayorIgual = 29;
  public static final int Bool = 6;
  public static final int Multiplicacion = 20;
  public static final int ParentesisApertura = 13;
  public static final int Suma = 17;
  public static final int Main = 54;
  public static final int AperturaBloque = 2;
  public static final int EspacioEnBlanco = 51;
  public static final int Igual = 30;
}

